// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-61zfEAjCJyJ0VsQXRM32aTtj9sqXrtg',
    appId: '1:589086067506:web:f092c4fb2e1798c216252b',
    messagingSenderId: '589086067506',
    projectId: 'senialesia',
    authDomain: 'senialesia.firebaseapp.com',
    storageBucket: 'senialesia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDxQjo3MdFTf7GP4pyVScOmtQIUCdbKWM',
    appId: '1:589086067506:android:48a6bc5a426c46f316252b',
    messagingSenderId: '589086067506',
    projectId: 'senialesia',
    storageBucket: 'senialesia.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-61zfEAjCJyJ0VsQXRM32aTtj9sqXrtg',
    appId: '1:589086067506:web:ff9937de85d60ecc16252b',
    messagingSenderId: '589086067506',
    projectId: 'senialesia',
    authDomain: 'senialesia.firebaseapp.com',
    storageBucket: 'senialesia.firebasestorage.app',
  );

}